### ISSUE TITLE
两边编译完之后生成的id是一样的，为啥啊

### ISSUE THREAD

**Issue by x1ntt** [chenjia404/go-p2ptunnel#1]
![image](https://user-images.githubusercontent.com/31797165/229774752-403f1281-fb8d-4b4a-bdfd-e1abf3ea463f.png)

![image](https://user-images.githubusercontent.com/31797165/229774850-0e02ce78-7282-42e9-a5ed-25cd01014e71.png)

一般情况下，不应该加了`-id`参数就当作连接端吗？
有刷新id的办法吗？id是什么计算来的？

**Comment by chenjia404** [comment]
节点私钥文件在当前目录下 user.key

**Comment by x1ntt** [comment]
> 节点私钥文件在当前目录下 user.key

原来如此 谢谢
另外，被链接端会出现
![image](https://user-images.githubusercontent.com/31797165/230558610-ded0d38c-2773-400e-ae22-7e6a69d9a043.png)

连接端会出现
![image](https://user-images.githubusercontent.com/31797165/230558693-a4b3b97a-d866-41e6-8446-8f6cb8ea985a.png)

这个是网络环境的问题吗？

**Comment by chenjia404** [comment]
网络相应端口是否打开了呢？

**Comment by x1ntt** [comment]
没明白是什么端口，目前两边防火墙都关闭了。有什么文档可以看到吗？就是实现原理这样的。

看它提示的错误似乎已经感知到了被连接端才对，但是io超时是什么情况呢？我在同局域网的设备中能连接到那个42701端口的（它似乎是一个http服务）

**Comment by chenjia404** [comment]
相应的端口都无法链接，重试看看呢，最新版加入了重连机制。

**Comment by x1ntt** [comment]
> 相应的端口都无法链接，重试看看呢，最新版加入了重连机制。

这次连接非常顺利，是做了什么修改吗？能和我简单说说原理吗？

**Comment by chenjia404** [comment]
> > 相应的端口都无法链接，重试看看呢，最新版加入了重连机制。
> 
> 这次连接非常顺利，是做了什么修改吗？能和我简单说说原理吗？

加了一些优化，增加链接的重新连接、广播这些，稳定好一些。

**Comment by x1ntt** [comment]
> > > 相应的端口都无法链接，重试看看呢，最新版加入了重连机制。
> > 
> > 
> > 这次连接非常顺利，是做了什么修改吗？能和我简单说说原理吗？
> 
> 加了一些优化，增加链接的重新连接、广播这些，稳定好一些。

感谢！
