### ISSUE TITLE
今天出现了 panic: expected chan in accept muxer

### ISSUE THREAD

**Issue by xf110** [chenjia404/go-p2ptunnel#3]
非常好用的穿透工具，速度很快，但很不稳定。连接端电脑多次重启后，被连接端必须重启程序才能连接成功。
p2ptunnel 0.0.1-"65f2a27"
buildTime "2023-04-20T09:52:34Z"
System version: amd64/windows
Golang version: go1.20.3
Your id: 12D3KooWEU6nnECrKJZ5fXM5baNLSrdftqxxxxxxxxx
连接成功12D3KooWJ9LbmrMs9Mq61demoi4DtHqqxxxxxxx
监听:127.0.0.1:5005
panic: expected chan in accept muxer

goroutine 97 [running]:
github.com/libp2p/go-libp2p/p2p/transport/quic.(*acceptLoopRunner).RmAcceptForVersion(0xc000271c98, 0x1e3ee8?)
        C:/Users/ADMIN/go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.1/p2p/transport/quic/virtuallistener.go:73 +0x14a
github.com/libp2p/go-libp2p/p2p/transport/quic.(*virtualListener).Close(0xc0002d6f40)
        C:/Users/ADMIN/go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.1/p2p/transport/quic/virtuallistener.go:33 +0x28
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr.func2.1()
        C:/Users/ADMIN/go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.1/p2p/net/swarm/swarm_listen.go:117 +0x117
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr.func2()
        C:/Users/ADMIN/go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.1/p2p/net/swarm/swarm_listen.go:130 +0x49c
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).AddListenAddr
        C:/Users/ADMIN/go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.1/p2p/net/swarm/swarm_listen.go:106 +0x22a

**Comment by chenjia404** [comment]
增加一个自动重启怎么样，这样就影响不大，再加上限制链接数

**Comment by xf110** [comment]
> 增加一个自动重启怎么样，这样就影响不大，再加上限制链接数

我现在设置成nas(被连接端)每天6点定时重启go-p2ptunnel，办公室电脑(连接端)每天只开机一次，看看稳定性如何。限制链接数要怎么做？是连接端个数(电脑台数)吗？用了各种内网穿透，只有您这个软件符合我的需求，速度很快，p2p也相对安全。如果更稳定一点就更好了。感谢您的回复。
