### ISSUE TITLE
弄明白出错的原因了

### ISSUE THREAD

**Issue by xf110** [chenjia404/go-p2ptunnel#4]
![image](https://user-images.githubusercontent.com/59716770/235300067-bfbc0333-0505-49b7-9be9-71d3cd53d132.png)

我不会编译，为了用这么优秀的软件，百度了编译方法，在电脑上编译了自己所需要的win版和nas的arm64版，发现您的比较小。我自己编译的版本没有任何错误。用您压缩过的还是会出现原来的问题（连接端断开再连接，反复超过3-5次，必须要重启被连接端，否则显示连接成功，实则没成功）。已经反复测试十几次，这是偶然发现的。我会继续测试。

**Comment by chenjia404** [comment]
我编译的也是基于最新版的go，应该没有区别啊，我增加一个版本，增加的重试机制。
https://github.com/chenjia404/go-p2ptunnel/releases/tag/v0.0.2
